### PR TITLE
fix bugs and update to new scrap

### PR DESCRIPTION
**Pull request by hhaoyan**
README: use new scrapy middleware class
randomproxy: raise error when no proxies are available
randomproxy: del in dict: ValueError=>KeyError

### CODE REVIEW

**Comment by chiragmatkar** [comment]
@hhaoyan  There is an exception handling it .If you don't wish to handle it you can just put

**Comment by hhaoyan** [comment]
I suppose this does exactly the same thing. Just don't quite understand why
use ValueError instead of KeyError.

**Comment by chiragmatkar** [comment]
try :
    pass
except (ValueError,KeyError):
    pass

**Comment by hhaoyan** [comment]
Where does “ValueError" come from?

**Comment by watermelonjuice** [comment]
Yeah, shouldn't it be KeyError?

**Pull request merged**
